[package]
name = "hello_world"
version = "0.1.0"
edition = "2018"

[dependencies]
axum = "0.2.5"
tokio = { version = "1.11.0", features = ["full"] }
clap = { version = "3.0.0-beta.4", features = ["unstable"] }
