name: boilerplaite ci
on: [push, pull_request]
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 1.19.x
    - uses: actions/checkout@v3
    - run: go vet ./boilerplate.go ./cmd/...
    - uses: golangci/golangci-lint-action@v3.2.0
      with:
        version: latest
        skip-build-cache: true
        skip-pkg-cache: true
  vulncheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 1.19.x
    - uses: actions/checkout@v3
    - run: go install golang.org/x/vuln/cmd/govulncheck@latest
    - run: govulncheck ./boilerplate.go ./cmd/...
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 1.19.x
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - run: go test -race ./boilerplate.go ./cmd/...
